{% set name = "sysv_ipc" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f063cbd36ec232032e425769ebc871f195a7d183b9af32f9901589ea7129ac3
  patches:
    # AttributeError: module 'distutils.sysconfig' has no attribute 'get_config_h_filename'
    - get_config_h_filename.patch
    - last_receive_pid_skip.patch

build:
  number: 6
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - sysv_ipc
  source_files:
    - tests
    - tests/*
  requires:
    - nose
  commands:
    - nosetests -sv --nologcapture tests/

about:
  home: https://github.com/osvenskan/sysv_ipc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sysv_ipc gives Python programs access to System V semaphores, shared memory and message queues

  description: |
    Sysv_ipc gives Python programs access to System V semaphores, shared memory 
    and message queues.
  doc_url: http://semanchuk.com/philip/sysv_ipc/
  dev_url: https://github.com/osvenskan/sysv_ipc

extra:
  recipe-maintainers:
    - langmm
