# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangpython2.7
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython2.7
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "q6jRz4wOTIs/xfFZwJxvs2FqkTO4dvW76dBBdBgdHygMmPFBSQcrhdDwfuYQqfHNFVFaYJIPQL7rmvOah9Fsz+WQDpITwiiX8vS1IdjSSmZzTybPJX7ojtirtPrqeWpHarPDFlWcSSFSeqApuH49o+BRvrElyU6G0mwL1IxUS6BUZbt5VnxnaNF0y6yLSO3P9B0956av8onNtjQ779dRTlfD0ZWgc9jHcTrdHVZdbxBM5dJvkby6nFM7smZ/YPgJY5WoEm4+TCaDpolGeOhfkk8b1r+6zrVydsCzuah1abgC/K4mhfbdRY0KC28wh7oqOOnpAqASSLurzohDJf/XulVpHadVb89gud+Qng9zUlliBtqp1RrAxqt2pBj+us2an6MXp3blHJkkYZyD0IEEhTKVMQxtrhgsn9KFu/ivscWmwk9HNjt+ArKjUu2jMyY/Ge1QreU06nawyLUrkQFa1oKHmwkNYJa9SQomrieNkHh993HN21Ccy1Op0jx7oTiX0qRYb4CNSUJXMN7uqNEfqgyMthU1bhs+yFS4I3XtKqVZn1R1eOU2oCyqccD+HeVO2d88Yrb91rZ1ILcP8FVa9J+k4rpp/AKlq0FL+AUNv5reg/5QLGNoBeXMq9irw+zY3WNlMLeAMcvZHKpuVNL+UH5k2ofI3O32bsaE7RDLnuk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
