travis:
  secure:
    BINSTAR_TOKEN: q6jRz4wOTIs/xfFZwJxvs2FqkTO4dvW76dBBdBgdHygMmPFBSQcrhdDwfuYQqfHNFVFaYJIPQL7rmvOah9Fsz+WQDpITwiiX8vS1IdjSSmZzTybPJX7ojtirtPrqeWpHarPDFlWcSSFSeqApuH49o+BRvrElyU6G0mwL1IxUS6BUZbt5VnxnaNF0y6yLSO3P9B0956av8onNtjQ779dRTlfD0ZWgc9jHcTrdHVZdbxBM5dJvkby6nFM7smZ/YPgJY5WoEm4+TCaDpolGeOhfkk8b1r+6zrVydsCzuah1abgC/K4mhfbdRY0KC28wh7oqOOnpAqASSLurzohDJf/XulVpHadVb89gud+Qng9zUlliBtqp1RrAxqt2pBj+us2an6MXp3blHJkkYZyD0IEEhTKVMQxtrhgsn9KFu/ivscWmwk9HNjt+ArKjUu2jMyY/Ge1QreU06nawyLUrkQFa1oKHmwkNYJa9SQomrieNkHh993HN21Ccy1Op0jx7oTiX0qRYb4CNSUJXMN7uqNEfqgyMthU1bhs+yFS4I3XtKqVZn1R1eOU2oCyqccD+HeVO2d88Yrb91rZ1ILcP8FVa9J+k4rpp/AKlq0FL+AUNv5reg/5QLGNoBeXMq9irw+zY3WNlMLeAMcvZHKpuVNL+UH5k2ofI3O32bsaE7RDLnuk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
