travis:
  secure:
    BINSTAR_TOKEN: hcxGSh1QSW/AfAjkT3mZVO+AqQW7Ftx0DDGJy86pAJ2IZOaw9sqd1PikR0mlsDBnADN7lRBXH55KLiRLO70/FQveEW3auHLITk1dq1EE5AItr7XHdQzmmpWdJUGQMaWB16pslNusrWuMphCWzi5FViBXdt89r2QfufJJBq4eIyAvt5LSlZsovojrdqGjkHXqV3jnTex4hGsnnWOEu5n+4X84nalrj04TNmgd1FvLXNfYy+oXaN7WeOqWUemRIEnNU+xybvI+RCGn3RRVEExjp9uSsSkSicK6SgNqUKnknepU/+jRBlwgMP/0PIW6cvaLlkawonPk/3naFCc2wMHDAxEUeeBaOsSrn3UWV6bd1d/Tv6S3rr/IvF9tN6ru2jkmjD+JwDqsn+J1sfjvAWdQrBXQjpfsY5ouUwcSv9pMiGkB9mIwjBlOn9AK8MAg7hSPV0G4StwPpR30cjlCRuZekLnRYujYDDyYmsmJV6JluykQCS/mBaLp61ihmF5guhp4Kr5QpMMZobCOk3fvXHS9fTqHoJnsI7fqxQoJ64DX705C3oc9CPSQdGx3U2GAGG4p3xSk8iVRl4ZsGaVGnHQ7W01RIC9moNOuwmbxeZXSfiy9VXzcdDjej3sCD6wxyTsYO8JQd040Pt39znuyJ4IUpjd3lamvCqkUa+yz5lH1GDw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
