build_platform:
  osx_arm64: osx_64
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
  win: azure
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test_on_native_only: true
conda_build:
  pkg_format: '2'
